# Generated by Django 3.1.5 on 2021-01-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=300, unique=True)),
                ('gitlink', models.CharField(max_length=300, unique=True)),
                ('premium', models.BooleanField(default=False)),
                ('bloglink', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
